### ISSUE TITLE
Thanks for sharing!

### ISSUE THREAD

**Issue by yizhiheng** [Him-2C/hackintosh-opencore-asus-h470-I-by-him-2c#1]
Hi, I'd like to know the completeness of your EFI. Everything works beside bluetooth and usbc audio jack? Also are you using OC 0.6.0?

 Thanks

**Comment by Him-2C** [comment]
The back jack is work, but the front is not and Bluetooth I use http://www.orico.cc/usmobile/product/detail/id/3425

**Comment by Him-2C** [comment]
try with last update
https://github.com/Him-2C/hackintosh-opencore-asus-h470-I-by-him-2c/releases/tag/1.1.0

**Comment by yizhiheng** [comment]
Thanks! I will give a try on weekend. I will report back if I find anything!

Thanks for your sharing again!
